### ISSUE TITLE
Limit item name length

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#125]

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/3422d3503a58907fe6aa419b7924afc3827677da

cc @Pennycrumb

**Comment by Pennycrumb** [comment]
Tested, still allowed to name and mint an item with a long name, but only shows up on Edit Profile page.


![Screenshot 2023-10-25 01 19 29](https://github.com/macterra/artx-market/assets/147219681/90e23b3d-a77d-4b30-b5d0-48b2e63e6d6e)

![Screenshot 2023-10-25 01 18 21](https://github.com/macterra/artx-market/assets/147219681/3a0e59e8-bc08-4671-b49c-60c73c93538a)

**Comment by macterra** [comment]
Done in https://github.com/macterra/artx-market/commit/4c145d8e174f9f96f637ff9dc7e7ceb5c16698a3

**Comment by Pennycrumb** [comment]
Tested and fixed
