### ISSUE TITLE
Limit collection name length

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#129]
![Screenshot 2023-10-25 01 18 21](https://github.com/macterra/artx-market/assets/147219681/36e1f7bc-5a7e-4fd2-a695-095c33373e31)
![Screenshot 2023-10-25 01 19 09](https://github.com/macterra/artx-market/assets/147219681/c58ad14e-9ba1-4ea2-b2ba-7c5a11d340bb)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/4c145d8e174f9f96f637ff9dc7e7ceb5c16698a3

**Comment by Pennycrumb** [comment]
Tested and fixed
