### ISSUE TITLE
Move Edit Profile button to same side of the site as Profile button

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#130]
Less movement with mouse going back and forth across the site

**Comment by macterra** [comment]
The Profile button in the main menu is now replaced by "Edit Profile" when you are viewing your own profile.

![image](https://github.com/macterra/artx-market/assets/434644/8a0c5bc6-1c1a-417e-a9d6-521eb02bd47c)

The old Edit Profile button is replaced by "Edit Collections"

Done in https://github.com/macterra/artx-market/commit/917e0a9ac3ea76484976be1b48409d959cd3869e

**Comment by Pennycrumb** [comment]
tested
