### ISSUE TITLE
Links Broken After Buying credits.

### ISSUE THREAD

**Issue by santyr** [macterra/artx-market#146]
Running Chromium-browser:

[Screencast from 2023-10-30 08-24-25.webm](https://github.com/macterra/artx-market/assets/792024/602da37c-515a-45e3-a110-40bcb21a9c2f)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/23f53e735e44359024061c6f72adf508778b2256

cc @santyr
