### ISSUE TITLE
Prevent spamming nostr

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#161]
Limit announcements of listings of editions on the same token to 1 per hour

**Comment by macterra** [comment]
It seems nostr relays will do some limiting, e.g. one 2 of 3 of these listings were distributed

https://primal.net/e/note1k0e2s5z7s0d48n3a0jaz5a29xr4zwd8nxqu9ydw6q98t35pk3vtq2pjguj

**Comment by santyr** [comment]
Perhaps charging additional credits for announcements might be a way to limit.  It would be like paying a small fee for advertising, and users would have to opt in to announcements.  Maybe one free in X amount of time with additional paid?

**Comment by macterra** [comment]
Done in https://github.com/macterra/artx-market/commit/c2cba91eec1640237fa149aa0bff35df14f9c4ce
