### ISSUE TITLE
Recenter # of items on page 

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#167]
![20231108_012201](https://github.com/macterra/artx-market/assets/147219681/914da0eb-4810-4d7a-906b-5400b4b47681)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/21cbfccbd867ba3176bef2584639050a7c50b2c9

**Comment by Pennycrumb** [comment]
Tested
