### ISSUE TITLE
Move Remove button to 

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#168]

**Comment by Pennycrumb** [comment]
Create pop up that states that a collection cannot be removed unless it is empty

![20231108_011932](https://github.com/macterra/artx-market/assets/147219681/c09d275d-d561-4cb5-b1c1-f48434836f34)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/634d0bb2fbc7dafa68cb54f6bd79c3c47172ba59

**Comment by Pennycrumb** [comment]
Tested
