### ISSUE TITLE
Create a Scroll to Top Button

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#173]

**Comment by macterra** [comment]
Done in https://github.com/macterra/artx-market/commit/30663263e16b7a15476c1ed651049dcf4887b233

**Comment by Pennycrumb** [comment]
Partially covered by footer on mobile
![Screenshot_20231117_001223_Chrome](https://github.com/macterra/artx-market/assets/147219681/493331cd-c269-40fe-8beb-f15aeb1d1797)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/94f5e2decde42b3688ef0f5791d9e70243e70617

**Comment by Pennycrumb** [comment]
Tested
