### ISSUE TITLE
Centre Recent Listings under Art Market 

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#179]
![20231114_000741](https://github.com/macterra/artx-market/assets/147219681/32ead922-f083-44d4-8585-25ad9cc12649)

**Comment by macterra** [comment]
Fixed by moving site name to logo on the far left.
https://github.com/macterra/artx-market/commit/75a0ba0dd8c53b5993e634b407672e038891a9d5

**Comment by Pennycrumb** [comment]
tested
