### ISSUE TITLE
Account name covers ArtX logo on mobile

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#190]
![Screenshot_20231122_233818_Gallery](https://github.com/macterra/artx-market/assets/147219681/a06419f1-29d3-449e-99a0-6f9341415dad)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/2bd4e2720457f9bde7ee9f44b97ad254a25e0326

**Comment by macterra** [comment]
Moved logout under the "hamburger" menu 
![image](https://github.com/macterra/artx-market/assets/434644/a7cd4f07-9f01-4070-b4c0-ad0ecd0edee1)

**Comment by Pennycrumb** [comment]
Tested
