### ISSUE TITLE
Add Credits button needs better spacing

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#191]
![Screenshot_20231122_233818_Gallery](https://github.com/macterra/artx-market/assets/147219681/1719f0d7-38e8-4ea4-be04-2057346d762a)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/69ec9224b3012bf04e729491f7d30e9078124d3f

**Comment by Pennycrumb** [comment]
tested
