### ISSUE TITLE
Join our Discord link is broken

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#194]
![Screenshot_20231122_200958_Discord](https://github.com/macterra/artx-market/assets/147219681/a384b5f1-2309-41d4-95d6-1d9d434c5bf2)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/4456a1fc8b92d6de9be8d9ebdf33a36330a8f80e

**Comment by Pennycrumb** [comment]
Tested
