### ISSUE TITLE
QR code for lightning login is not centred on mobile 

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#195]
![Screenshot_20231122_200725_Chrome](https://github.com/macterra/artx-market/assets/147219681/96fb93ac-45f0-4f9a-b257-95f4f7d05c47)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/68c1d0cce15d2b4bdd2c6f67988d7154d0ee90fc

**Comment by Pennycrumb** [comment]
Tested
