### ISSUE TITLE
Too much information on page on mobile

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#210]
![Screenshot_20231212_231004_Chrome](https://github.com/macterra/artx-market/assets/147219681/31d47685-88bc-4c55-921a-8d6cc55b60ac)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/67179d5deea5d9e4d4f1b6fb440313c4f2db64f9

**Comment by Pennycrumb** [comment]
tested
