### ISSUE TITLE
Issues adding url to profile

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#212]
![20231219_233936](https://github.com/macterra/artx-market/assets/147219681/9640ff3c-fb63-49b2-9cfa-9a03e9db607a)

![20231219_233846](https://github.com/macterra/artx-market/assets/147219681/d1f12297-b0f0-4b70-aeab-271ac1c8e51a)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/3ae5199dac811a63480f020489d3c1181c061cfc

**Comment by Pennycrumb** [comment]
tested
