### ISSUE TITLE
Prevent upload abuse

### ISSUE THREAD

**Issue by macterra** [macterra/artx-market#29]
A bad actor could overwhelm the server with infinite uploads

**Comment by santyr** [comment]
Luninai suggests it is, "...possible to implement an image uploading fee based on the file size using the same invoicing methods that the app already uses. The Lightning Network, which is used by the app for transactions, allows for micro-transactions. This is perfect for charging users based on the size of the files they upload.

Here's a high-level idea of how you can implement this:

Calculate the Fee: Determine a cost per unit of data (e.g., satoshis per kilobyte). When a user uploads an image, calculate the size of the image and multiply it by the cost per unit to determine the total fee.

Generate an Invoice: Using the same method the app uses to generate invoices for other transactions, create an invoice for the upload fee.

Wait for Payment Confirmation: Before the image is actually uploaded to the server or IPFS, wait for confirmation that the invoice has been paid.

Upload the Image: Once the payment is confirmed, proceed with the upload process.

Remember to clearly communicate this fee to your users. It might be a good idea to calculate the fee and display it to the user before they confirm the upload, so they know exactly how much they'll be charged.

This approach incentivizes users to be mindful of their upload usage, and it also provides a revenue stream that can help to offset the costs of running the server and maintaining the IPFS nodes."

**Comment by macterra** [comment]
Maybe when a new user joins they get 100 free credits that enable them to upload 100MB of assets. When the credits run out they can buy more upload credits for 10 sats each or something.

**Comment by macterra** [comment]
Maybe also use credits for minting so new users can get started and bootstrap without funding their lightning wallet.

**Comment by macterra** [comment]
Done in https://github.com/macterra/artx-market/commit/ab97e1c9752f9d77dfc6f2dab0b01fc7bf99ccb7
