### ISSUE TITLE
No record of Minted items

### ISSUE THREAD

**Issue by Pennycrumb** [macterra/artx-market#93]
![image](https://github.com/macterra/artx-market/assets/147219681/a44dbd6b-79be-4200-8df1-487c76e2cd22)

**Comment by macterra** [comment]
Fixed in https://github.com/macterra/artx-market/commit/c549bae2698ca5ccc9f20252d2d0897e6557adf6

**Comment by macterra** [comment]
discord test

**Comment by Pennycrumb** [comment]
tested
